name: Build & Publish Docs with Sphinx

on:
  push:
    branches:
    - master

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Convert README and Move
      run: |
        m2r README.md
        sed -i 's/.. image:: examples/.. image:: ../../examples/g' README.rst
        mv README.rst docs/source

    - name: Build sphinx documentation
      run: |
        cd docs
        make html
    
    - name: Deploy
      uses: JacksonMaxfield/github-pages-deploy-action-python@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs/_build/html # The folder the action should deploy. This example folder is generated by Sphinx
