name: Build & Publish Docs with Sphinx

on:
  push:
    branches:
    - master

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies & Convert README
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        m2r README.md

    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: ".. image:: examples"
        replace: ".. image:: ../../examples"
        include: "README.rst"
        
    - name: Move README.rst & Build sphinx documentation
      run: |
        mv README.rst docs/source
        cd docs
        make html

    - name: Push to gh-pages
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: docs/build/html
        github_token: ${{ secrets.ACCESS_TOKEN }}
